### ISSUE TITLE
'ConnectionRefusedError' is not defined

### ISSUE THREAD

**Issue by oovs** [unixsurfer/haproxyadmin#12]
Throws an exception on `Python 2.7.9`:
```
  File "/usr/local/lib/python2.7/dist-packages/haproxyadmin/haproxy.py", line 110, in __init__
    if is_unix_socket(_file) and connected_socket(_file):
  File "/usr/local/lib/python2.7/dist-packages/haproxyadmin/utils.py", line 179, in connected_socket
    except (ConnectionRefusedError, PermissionError, socket.timeout, OSError):
NameError: global name 'ConnectionRefusedError' is not defined
```

Packages version:
```
haproxyadmin (0.2.1)
six (1.11.0)
```

**Comment by unixsurfer** [comment]
``ConnectionRefusedError`` exception is not available in Python2, only in Python3. Thus you get that error. I guess I have to switch to ``socket.error`` exception which is present in both versions of Python.

**Comment by oovs** [comment]
I've applied the PR #8 locally because I require quick fix and I could say it works fine.

**Comment by unixsurfer** [comment]
A simpler solution was done by https://github.com/unixsurfer/haproxyadmin/commit/9227df29495e7ba079c5f8ca3f6616e82e91fd81
