### ISSUE TITLE
AttributeError: module 'haproxyadmin.haproxy' has no attribute 'STATE_READY'

### ISSUE THREAD

**Issue by m4druga** [unixsurfer/haproxyadmin#16]
The setstate function only worked when I added: "from haproxyadmin.server import *" on haproxy.py.
Probably this is not the best way to solve this problem.

**Comment by unixsurfer** [comment]
Can you show me the code which triggered this?

**Comment by m4druga** [comment]
#!/usr/bin/python3`
#-*- coding: utf-8 -*-

from haproxyadmin import haproxy

hap = haproxy.HAProxy(socket_dir='/run/haproxy')
server = hap.server('server0', backend='backend0')[0]
server.setstate(haproxy.STATE_READY)

**Comment by unixsurfer** [comment]
You have to first import STATE_READY:
```
from haproxyadmin import STATE_READY
```
and then
```
server.setstate(STATE_READY)
```

This a documentation bug which I need to fix. Sorry for the trouble.

**Comment by m4druga** [comment]
Now it worked!

Thank you for your time!
