### ISSUE TITLE
request information : rest api feature 

### ISSUE THREAD

**Issue by x-077** [unixsurfer/haproxyadmin#17]
Hello, 

Do you plan to expose an REST API for this great plugin with flask for example ? 

Thanks.

**Comment by unixsurfer** [comment]
Hi @matth-c3 ,

I guess you want an HTTP interface which you send PATCH requests to adjust properties(enable/disable status, change weight and etc) and GET requests to retrieve information. Am I right? What is the use-case here?

I am currently adding support to query HAProxy over TCP socket in additions to UNIX sockets, so we will be able to query remote haproxy servers. Is it something that can accommodate your needs?

Cheers,
Pavlos

**Comment by x-077** [comment]
Hello @unixsurfer , 

Thanks for your answer, Yes that's exactly that, to provide the ability to send PATCH requests to adjust properties(enable/disable status, change weight and etc) and GET requests to retrieve information.

THanks.

**Comment by unixsurfer** [comment]
Hi,
Thanks for the confirmation, but what is the use-case?

**Comment by unixsurfer** [comment]
Right now I don't have any plans to add this functionality and my time is unfortunately very limited.

**Comment by x-077** [comment]
Hello, 

To scale up and down the frontend/backend in haproxy when scalling services. 

It could be triggered when new instance is add/remove in a cluster. ( AWS autoscalling for example )

I understand the constrain, thanks anyway.

**Comment by x-077** [comment]
I was thinking of flask as it's using definitions/methods as endpoint, unfortunately I did not do python in a long time, maybe it could be worst to give a try on my side and make a pr

**Comment by unixsurfer** [comment]
OK, I understand the use case. But for this specific case of scaling up/down frontend and backends, you need to reload haproxy as such operations require a reload. So, I don't quite understand what you need to change via haproxyadmin. I guess you have to do some operations prior to scaling.

As I wrote above, I am going to add support for TCP sockets, so you can achieve what you want. I acknowledge and understand that an HTTP API can be integrated more easily into existent tools.

**Comment by x-077** [comment]
Hello @unixsurfer , 

No problem at all. Closing the ticket. 

Thanks.
