### ISSUE TITLE
`show_map` on a cleared map returns `['']`

### ISSUE THREAD

**Issue by nfirvine** [unixsurfer/haproxyadmin#4]
``` python
import haproxyadmin
hap = haproxyadmin.haproxy.HAProxy(socket_file="/var/lib/haproxy/stats")
hap.clear_map(1) 
hap.show_map("/etc/haproxy/backend.map") # => ['']
```

Expected it to return `[]`

**Comment by unixsurfer** [comment]
HAProxy returns an empty string and I simply return that. In that case, I should strip it and return an empty list. What do you think?

**Comment by unixsurfer** [comment]
Fixed with https://github.com/unixsurfer/haproxyadmin/commit/bc93ee6352171a324db4914f15df21dd11582337
