### ISSUE TITLE
`show_map(map)` should return a list of tuples

### ISSUE THREAD

**Issue by nfirvine** [unixsurfer/haproxyadmin#5]
It returns `['<id> <key> <value>', ...]`. Any reason not to return something like `[(id, key, value), ...]`?

**Comment by unixsurfer** [comment]
To be honest, I didn't have a specific reason back then. Do you see any benefits returning a tuple?

**Comment by nfirvine** [comment]
Jeez, I haven't worked on Haproxy stuff for ages. The tuple part doesn't matter so much, just that it's parsed.
